name: gnn-lspe-jax
dependencies:
 - python=3.9
 - pip
# - flax
 - matplotlib
 - scipy
# - conda-forge::optax 
## Jax version 0.3.24 required until 0.0.9 haiku becomes available via Conda, as removal of jax_experimental_name_stack in 0.3.25 causes issues
# - conda-forge::jax=0.3.24
# - conda-forge::dm-haiku=0.0.8
 - numpy=1.22
 - conda-forge::wandb
# Pytorch and dgl for dataset loading
 - pytorch
# - dglteam::dgl
# For some reason dglteam::dgl doesn't seem to be available as of 28 Jan, so moving to pip for now
 - pip:
   - jraph
   - flax
   - dm-haiku
   - dgl