name: gnn-lspe-jax
dependencies:
 - python=3.9
 - pip
 - scipy
 - numpy=1.22
 - conda-forge::wandb
 - pytorch # Pytorch and dgl are for dataset loading
 - pip:
   - jraph
   - dm-haiku
   - dgl==0.9.1 ##DGL 1 breaks ZINC dataset
   - optax
   - ogb==1.3.1